#!/bin/sh -e

NEW_KERNEL="$1"
OLD_KERNEL=${"$(file -bL /boot/vmlinuz | sed 's/.*version //;s/ .*//')"}
kloc="$2"
rdloc="/boot/initrd.img-$ver"

MORTAR=/usr/local/sbin/mortar

clean_boot() {
    #Remove unneccessary boot partition clutter
    local EFI="/boot/efi/EFI"
    find $EFI -type d -name "Recovery*" -exec rm -r "{}" \;
    find $EFI -type d -name "Pop_OS*" -exec rm -r "{}" \;
    find $EFI -type f -name "Pop_OS*" -exec rm -r "{}" \;
    find $EFI -type d -name "c93*" -exec rm -r "{}" \;
    find /boot/xbootldr -type d -name "c93" -exec rm -r "{}" \;
}

if ! [ -e "$kloc" ]; then kloc="/boot/vmlinuz-$ver"; fi
if ! [ -e "$kloc" ]; then echo "Can't find the new kernel."; exit 1; fi
if ! [ -e "$rdloc" ]; then echo "Can't find the new initrd.img."; exit 2; fi

#$MORTAR install-kernel "$ver";

clean_boot && exit 0;