#!/bin/sh -e
#This is utterly fucked
ver="$1"
kloc="$2"
rdloc="/boot/initrd.img-$ver"
MORTAR=/usr/local/sbin/mortar 

if ! [ -e "$kloc" ]; then kloc="/boot/vmlinuz-$ver"; fi
if ! [ -e "$kloc" ]; then echo "Can't find the new kernel."; exit 1; fi
if ! [ -e "$rdloc" ]; then echo "Can't find the new initrd.img."; exit 2; fi

clean_boot() {
    # #Remove unneccessary boot partition clutter
[ -d /boot/efi/EFI/Recovery* ] && rm -r /boot/efi/EFI/Recovery*;
[ -d /boot/efi/EFI/Pop_OS* ] && rm -r /boot/efi/EFI/Pop_OS-*;
[ -f /boot/efi/loader/entries/Pop_OS-* ] && rm /boot/efi/loader/entries/Pop_OS-*;
[ -d /boot/efi/4* ] && rm -r /boot/efi/c93*;
[ -d /boot/xbootldr/4* ] && rm -r /boot/xbootldr/c93;
}

$MORTAR install-kernel
$MORTAR install-alternates
$MORTAR bootctl install
clean_boot