#!/bin/sh
KERNEL="$(basename "$( sudo readlink -f /boot/vmlinuz )")"
ALT="$(basename "$( sudo readlink -f /boot/vmlinuz.old )")"

clean_boot() {
    # #Remove unneccessary boot partition clutter
[ -d "/boot/efi/EFI/Recovery*" ] && rm -r /boot/efi/EFI/Recovery*;
[ -d "/boot/efi/EFI/Pop_OS*" ] && rm -r /boot/efi/EFI/Pop_OS-*;
[ -d "/boot/efi/loader/entries/Pop_OS-*" ] && rm -r /boot/efi/loader/entries/Pop_OS-*;
[ -d "/boot/efi/4*" ] && rm -r /boot/efi/4bfbf10fcdd6d3152ccf60f75f8b32e7;
[ -d "/boot/xbootldr/4*" ] && rm -r /boot/xbootldr/4bfbf10fcdd6d3152ccf60f75f8b32e7;
}

sign_kernel() {
    echo "mortar: Installing $1 to ESP";
    mortar install-kernel "$1";
    clean_boot;
    exit 0
}
sign_alt() {
    echo "mortar: Installing $1 to ESP";
    mortar install-alternates;
    clean_boot;
    exit 0;
}

mortar help > /dev/null 2>&1 || exit 0
[ "$KERNEL" = "vmlinuz-$1" ] && sign_kernel $1;
[ "$ALT" = "vmlinuz-$1" ] && sign_alt $1;

exit 0