#!/bin/sh
KERNEL=${1:="$(file -bL /boot/vmlinuz | sed 's/.*version //;s/ .*//')"}
ALT=${1:="$(file -bL /boot/vmlinuz.old | sed 's/.*version //;s/ .*//')"}
MORTAR=/usr/local/sbin/mortar

clean_boot() {
    #Remove unneccessary boot partition clutter
    local EFI="/boot/efi/EFI"
    find $EFI -type d -name "Recovery*" -exec rm -r "{}" \;
    find $EFI -type d -name "Pop_OS*" -exec rm -r "{}" \;
    find $EFI -type f -name "Pop_OS*" -exec rm -r "{}" \;
    find $EFI -type d -name "c93*" -exec rm -r "{}" \;
    find /boot/xbootldr -type d -name "c93" -exec rm -r "{}" \;
}

sign_kernel() {
    $MORTAR install-kernel "$KERNEL";
    clean_boot;
}
sign_alt() {
    $MORTAR install-alternates "$ALT";
    clean_boot;
}

$MORTAR help > /dev/null || exit 1;

[ "$1" = "$(file -bL /boot/vmlinuz | sed 's/.*version //;s/ .*//')" ] && sign_kernel;
[ "$1" = "$(file -bL /boot/vmlinuz.old | sed 's/.*version //;s/ .*//')" ] && sign_alt;
exit 0;